#!/usr/bin/with-contenv sh

[ -f /config/omglol.conf ] || exit 0

. /app/omglol.sh
. /config/omglol.conf

if [ "$DELETE_ON_STOP" == "true" ]; then
  echo "Deleting OMG.lol DNS record $DDNS_RECORD_NAME..."

  update=$(deleteDnsRecord $DDNS_RECORD_ID)

  if [ "$update" != 200 ]; then
    echo "ERROR: Failed to delete OMG.lol DNS record $DDNS_RECORD_NAME"
  else
    echo "OMG.lol DNS record $DDNS_RECORD_NAME deleted successfully."
  fi
else
  echo "Not going to delete the dns record. Deleting the dns record on container stop is disable by default."
fi
