#!/usr/bin/with-contenv sh

. /app/omglol.sh
. /config/omglol.conf

DnsIpAddress=$(getDnsRecordIp $DDNS_RECORD_ID)

if [ ! -z ${CUSTOM_LOOKUP_CMD+x} ]; then
  CurrentIpAddress=$(getCustomIpAddress)
elif [ ! -z ${INTERFACE+x} ]; then
  CurrentIpAddress=$(getLocalIpAddress)
else
  CurrentIpAddress=$(getPublicIpAddress)
fi

if [ "$CurrentIpAddress" != "$DnsIpAddress" ]; then
  echo "Updating OMG.lol DNS record $DDNS_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress..."
  update=$(updateDnsRecord $DDNS_RECORD_ID $DDNS_RECORD_NAME $CurrentIpAddress)

  if [ "$update" == "null" ]; then
    echo "ERROR: Failed to update OMG.lol DNS record $DDNS_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress"
  else
    echo "OMG.lol DNS record $DDNS_RECORD_NAME ($CurrentIpAddress) updated successfully."
  fi
  
else
  echo "No DNS update required for $DDNS_RECORD_NAME ($DnsIpAddress)."
fi
